<?php

/**
 * The admin-specific functionality of the plugin.
 *
 * @link       https://knowhalim.com
 * @since      1.0.0
 *
 * @package    Tourhand-jap-quiz
 * @subpackage Tourhand-jap-quiz/admin
 */

/**
 * The admin-specific functionality of the plugin.
 *
 * Defines the plugin name, version, and two examples hooks for how to
 * enqueue the admin-specific stylesheet and JavaScript.
 *
 * @package    Tourhand-jap-quiz
 * @subpackage Tourhand-jap-quiz/admin
 * @author     Halim <contact@knowhalim.com>
 */
class Tourhand_jap_quiz_Admin {

	/**
	 * The ID of this plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 * @var      string    $plugin_name    The ID of this plugin.
	 */
	private $plugin_name;

	/**
	 * The version of this plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 * @var      string    $version    The current version of this plugin.
	 */
	private $version;

	/**
	 * Initialize the class and set its properties.
	 *
	 * @since    1.0.0
	 * @param      string    $plugin_name       The name of this plugin.
	 * @param      string    $version    The version of this plugin.
	 */
	public function __construct( $plugin_name, $version ) {

		$this->plugin_name = $plugin_name;
		$this->version = $version;

	}

	/**
	 * Register the stylesheets for the admin area.
	 *
	 * @since    1.0.0
	 */
	public function enqueue_styles() {

		/**
		 * This function is provided for demonstration purposes only.
		 *
		 * An instance of this class should be passed to the run() function
		 * defined in Tourhand-jap-quiz_Loader as all of the hooks are defined
		 * in that particular class.
		 *
		 * The Tourhand-jap-quiz_Loader will then create the relationship
		 * between the defined hooks and the functions defined in this
		 * class.
		 */

		wp_enqueue_style( $this->plugin_name, plugin_dir_url( __FILE__ ) . 'css/tourhand-jap-quiz-admin.css', array(), $this->version, 'all' );

	}

	/**
	 * Register the JavaScript for the admin area.
	 *
	 * @since    1.0.0
	 */
	public function enqueue_scripts() {

		/**
		 * This function is provided for demonstration purposes only.
		 *
		 * An instance of this class should be passed to the run() function
		 * defined in Tourhand-jap-quiz_Loader as all of the hooks are defined
		 * in that particular class.
		 *
		 * The Tourhand-jap-quiz_Loader will then create the relationship
		 * between the defined hooks and the functions defined in this
		 * class.
		 */

		wp_enqueue_script( $this->plugin_name, plugin_dir_url( __FILE__ ) . 'js/tourhand-jap-quiz-admin.js', array( 'jquery' ), $this->version, false );

	}

}


/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class SimpleLearnJapaneseQuizSettings {
	private $simplelearnjapanesequiz_settings_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'simplelearnjapanesequiz_settings_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'simplelearnjapanesequiz_settings_page_init' ) );
	}

	public function simplelearnjapanesequiz_settings_add_plugin_page() {
		add_options_page(
			'Simple Learn Japanese Quiz Settings', // page_title
			'Simple Learn Japanese Quiz Settings', // menu_title
			'manage_options', // capability
			'simplelearnjapanesequiz-settings', // menu_slug
			array( $this, 'simplelearnjapanesequiz_settings_create_admin_page' ) // function
		);
	}

	public function simplelearnjapanesequiz_settings_create_admin_page() {
		$this->simplelearnjapanesequiz_settings_options = get_option( 'simplelearnjapanesequiz_settings_option_name' ); ?>

		<div class="wrap">
			<h2>Simple Learn Japanese Quiz Settings</h2>
			<p>Configure your settings to customize Simple Learn Japanese Quiz. Use [simplelearnjapanesequiz_display_form] to display in the frontend.</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'simplelearnjapanesequiz_settings_option_group' );
					do_settings_sections( 'simplelearnjapanesequiz-settings-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function simplelearnjapanesequiz_settings_page_init() {
		register_setting(
			'simplelearnjapanesequiz_settings_option_group', // option_group
			'simplelearnjapanesequiz_settings_option_name', // option_name
			array( $this, 'simplelearnjapanesequiz_settings_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'simplelearnjapanesequiz_settings_setting_section', // id
			'Settings', // title
			array( $this, 'simplelearnjapanesequiz_settings_section_info' ), // callback
			'simplelearnjapanesequiz-settings-admin' // page
		);
		add_settings_field(
			'headline_for_quiz_5', // id
			'Headline For Quiz', // title
			array( $this, 'headline_for_quiz_5_callback' ), // callback
			'simplelearnjapanesequiz-settings-admin', // page
			'simplelearnjapanesequiz_settings_setting_section' // section
		);
		add_settings_field(
			'introduction_text_0', // id
			'Introduction Text', // title
			array( $this, 'introduction_text_0_callback' ), // callback
			'simplelearnjapanesequiz-settings-admin', // page
			'simplelearnjapanesequiz_settings_setting_section' // section
		);

		add_settings_field(
			'start_button_text_eg_start_now_1', // id
			'Start Button Text (eg. Start Now)', // title
			array( $this, 'start_button_text_eg_start_now_1_callback' ), // callback
			'simplelearnjapanesequiz-settings-admin', // page
			'simplelearnjapanesequiz_settings_setting_section' // section
		);

		add_settings_field(
			'next_button_text_eg_next_2', // id
			'Next Button Text (eg. Next)', // title
			array( $this, 'next_button_text_eg_next_2_callback' ), // callback
			'simplelearnjapanesequiz-settings-admin', // page
			'simplelearnjapanesequiz_settings_setting_section' // section
		);

		add_settings_field(
			'submit_button_text_eg_get_your_result_3', // id
			'Submit Button Text (eg. Get your result)', // title
			array( $this, 'submit_button_text_eg_get_your_result_3_callback' ), // callback
			'simplelearnjapanesequiz-settings-admin', // page
			'simplelearnjapanesequiz_settings_setting_section' // section
		);

		add_settings_field(
			'after_quiz_message_4', // id
			'After Quiz Message', // title
			array( $this, 'after_quiz_message_4_callback' ), // callback
			'simplelearnjapanesequiz-settings-admin', // page
			'simplelearnjapanesequiz_settings_setting_section' // section
		);

		

		add_settings_field(
			'support_developer_by_displaying_credits_6', // id
			'Support developer by displaying credits?', // title
			array( $this, 'support_developer_by_displaying_credits_6_callback' ), // callback
			'simplelearnjapanesequiz-settings-admin', // page
			'simplelearnjapanesequiz_settings_setting_section' // section
		);

		/*add_settings_field(
			'store_score_to_show_average_result_7', // id
			'Store Score To Show Average Result?', // title
			array( $this, 'store_score_to_show_average_result_7_callback' ), // callback
			'simplelearnjapanesequiz-settings-admin', // page
			'simplelearnjapanesequiz_settings_setting_section' // section
		);*/
	}

	public function simplelearnjapanesequiz_settings_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['introduction_text_0'] ) ) {
			$sanitary_values['introduction_text_0'] = esc_textarea( $input['introduction_text_0'] );
		}

		if ( isset( $input['start_button_text_eg_start_now_1'] ) ) {
			$sanitary_values['start_button_text_eg_start_now_1'] = sanitize_text_field( $input['start_button_text_eg_start_now_1'] );
		}

		if ( isset( $input['next_button_text_eg_next_2'] ) ) {
			$sanitary_values['next_button_text_eg_next_2'] = sanitize_text_field( $input['next_button_text_eg_next_2'] );
		}

		if ( isset( $input['submit_button_text_eg_get_your_result_3'] ) ) {
			$sanitary_values['submit_button_text_eg_get_your_result_3'] = sanitize_text_field( $input['submit_button_text_eg_get_your_result_3'] );
		}

		if ( isset( $input['after_quiz_message_4'] ) ) {
			$sanitary_values['after_quiz_message_4'] = esc_textarea( $input['after_quiz_message_4'] );
		}

		if ( isset( $input['headline_for_quiz_5'] ) ) {
			$sanitary_values['headline_for_quiz_5'] = sanitize_text_field( $input['headline_for_quiz_5'] );
		}

		if ( isset( $input['support_developer_by_displaying_credits_6'] ) ) {
			$sanitary_values['support_developer_by_displaying_credits_6'] = $input['support_developer_by_displaying_credits_6'];
		}

		if ( isset( $input['store_score_to_show_average_result_7'] ) ) {
			$sanitary_values['store_score_to_show_average_result_7'] = $input['store_score_to_show_average_result_7'];
		}

		return $sanitary_values;
	}

	public function simplelearnjapanesequiz_settings_section_info() {
		
	}

	public function introduction_text_0_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="simplelearnjapanesequiz_settings_option_name[introduction_text_0]" id="introduction_text_0">%s</textarea>',
			isset( $this->simplelearnjapanesequiz_settings_options['introduction_text_0'] ) ? esc_attr( $this->simplelearnjapanesequiz_settings_options['introduction_text_0']) : 'Welcome to our survey.'
		);
	}

	public function start_button_text_eg_start_now_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="simplelearnjapanesequiz_settings_option_name[start_button_text_eg_start_now_1]" id="start_button_text_eg_start_now_1" value="%s">',
			isset( $this->simplelearnjapanesequiz_settings_options['start_button_text_eg_start_now_1'] ) ? esc_attr( $this->simplelearnjapanesequiz_settings_options['start_button_text_eg_start_now_1']) : 'Start Now'
		);
	}

	public function next_button_text_eg_next_2_callback() {
		printf(
			'<input class="regular-text" type="text" name="simplelearnjapanesequiz_settings_option_name[next_button_text_eg_next_2]" id="next_button_text_eg_next_2" value="%s">',
			isset( $this->simplelearnjapanesequiz_settings_options['next_button_text_eg_next_2'] ) ? esc_attr( $this->simplelearnjapanesequiz_settings_options['next_button_text_eg_next_2']) : 'Next'
		);
	}

	public function submit_button_text_eg_get_your_result_3_callback() {
		printf(
			'<input class="regular-text" type="text" name="simplelearnjapanesequiz_settings_option_name[submit_button_text_eg_get_your_result_3]" id="submit_button_text_eg_get_your_result_3" value="%s">',
			isset( $this->simplelearnjapanesequiz_settings_options['submit_button_text_eg_get_your_result_3'] ) ? esc_attr( $this->simplelearnjapanesequiz_settings_options['submit_button_text_eg_get_your_result_3']) : 'See Result'
		);
	}

	public function after_quiz_message_4_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="simplelearnjapanesequiz_settings_option_name[after_quiz_message_4]" id="after_quiz_message_4">%s</textarea>',
			isset( $this->simplelearnjapanesequiz_settings_options['after_quiz_message_4'] ) ? esc_attr( $this->simplelearnjapanesequiz_settings_options['after_quiz_message_4']) : 'Thank you for using our plugin.'
		);
	}

	public function headline_for_quiz_5_callback() {
		printf(
			'<input class="regular-text" type="text" name="simplelearnjapanesequiz_settings_option_name[headline_for_quiz_5]" id="headline_for_quiz_5" value="%s">',
			isset( $this->simplelearnjapanesequiz_settings_options['headline_for_quiz_5'] ) ? esc_attr( $this->simplelearnjapanesequiz_settings_options['headline_for_quiz_5']) : 'Find out your score!'
		);
	}

	public function support_developer_by_displaying_credits_6_callback() {
		?> <fieldset><?php $checked = ( isset( $this->simplelearnjapanesequiz_settings_options['support_developer_by_displaying_credits_6'] ) && $this->simplelearnjapanesequiz_settings_options['support_developer_by_displaying_credits_6'] === 'yes' ) ? 'checked' : '' ; ?>
		<label for="support_developer_by_displaying_credits_6-0"><input type="radio" name="simplelearnjapanesequiz_settings_option_name[support_developer_by_displaying_credits_6]" id="support_developer_by_displaying_credits_6-0" value="yes" <?php echo $checked; ?>> Yes</label><br>
		<?php $checked = ( isset( $this->simplelearnjapanesequiz_settings_options['support_developer_by_displaying_credits_6'] ) && $this->simplelearnjapanesequiz_settings_options['support_developer_by_displaying_credits_6'] === 'no' ) ? 'checked' : '' ; ?>
		<label for="support_developer_by_displaying_credits_6-1"><input type="radio" name="simplelearnjapanesequiz_settings_option_name[support_developer_by_displaying_credits_6]" id="support_developer_by_displaying_credits_6-1" value="no" <?php echo $checked; ?>> No</label></fieldset> <?php
	}

	public function store_score_to_show_average_result_7_callback() {
		?> <fieldset><?php $checked = ( isset( $this->simplelearnjapanesequiz_settings_options['store_score_to_show_average_result_7'] ) && $this->simplelearnjapanesequiz_settings_options['store_score_to_show_average_result_7'] === 'yes' ) ? 'checked' : '' ; ?>
		<label for="store_score_to_show_average_result_7-0"><input type="radio" name="simplelearnjapanesequiz_settings_option_name[store_score_to_show_average_result_7]" id="store_score_to_show_average_result_7-0" value="yes" <?php echo $checked; ?>> Yes</label><br>
		<?php $checked = ( isset( $this->simplelearnjapanesequiz_settings_options['store_score_to_show_average_result_7'] ) && $this->simplelearnjapanesequiz_settings_options['store_score_to_show_average_result_7'] === 'no' ) ? 'checked' : '' ; ?>
		<label for="store_score_to_show_average_result_7-1"><input type="radio" name="simplelearnjapanesequiz_settings_option_name[store_score_to_show_average_result_7]" id="store_score_to_show_average_result_7-1" value="no" <?php echo $checked; ?>> No</label></fieldset> <?php
	}

}
if ( is_admin() )
	$mypluginname_settings = new SimpleLearnJapaneseQuizSettings();

/* 
 * Retrieve this value with:
 $simplelearnjapanesequiz_settings_options = get_option( 'simplelearnjapanesequiz_settings_option_name' ); // Array of All Options
 $introduction_text= $simplelearnjapanesequiz_settings_options['introduction_text_0']; // Introduction Text
 $start_button_text = $simplelearnjapanesequiz_settings_options['start_button_text_eg_start_now_1']; // Start Button Text (eg. Start Now)
 $next_button_text = $simplelearnjapanesequiz_settings_options['next_button_text_eg_next_2']; // Next Button Text (eg. Next)
 $submit_button_text = $simplelearnjapanesequiz_settings_options['submit_button_text_eg_get_your_result_3']; // Submit Button Text (eg. Get your result)
 $after_quiz_message = $simplelearnjapanesequiz_settings_options['after_quiz_message_4']; // After Quiz Message
 $headline_for_quiz = $simplelearnjapanesequiz_settings_options['headline_for_quiz_5']; // Headline For Quiz
 $support_developer = $simplelearnjapanesequiz_settings_options['support_developer_by_displaying_credits_6']; // Support developer by displaying credits?
 * $store_score_to_show = $simplelearnjapanesequiz_settings_options['store_score_to_show_average_result_7']; // Store Score To Show Average Result?
 */

